name: Docker Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 签出代码
      - name: Checkout
        uses: actions/checkout@v3
      # 设置QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # 设置Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      # 登录DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # 打包镜像并推送DockerHub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.cn-shenzhen.aliyuncs.com/kousyoukun/spider-api:${{ github.ref_name }}-build-${{ github.run_number }}
